[default]
s3_bucket = "s3-bucket-name"
api_base_url = "https://payment-provider.com/reports/"

curated_database = "curated"
curated_table = "payments"
curated_partition_column = "payment_date"
curated_output_path = "s3://{{ s3_bucket }}/{{ curated_database }}/{{ curated_table }}"

enriched_database = "enriched"
enriched_table = "daily_game_payments"
enriched_partition_column = "payment_date"
enriched_output_path = "s3://{{ s3_bucket }}/{{ enriched_database }}/{{ enriched_table }}"

[development]
bucket_name = "dev-s3-bucket"
api_base_url = "https://dev-payment-provider.com/reports/"

[production]
bucket_name = "prod-s3-bucket"
api_base_url = "https://payment-provider.com/reports/"
